### ISSUE TITLE
horizontallySpaced function return type not compatible with typestyle

### ISSUE THREAD

**Issue by piotrwitek** [typestyle/csstips#6]
Hi,
I stumbled upon issue with horizontallySpaced method, it's return type is not compatible with typestyle.style function which expect CSSProperties type.

I identified the problem in misplaced type assertion on this line: https://github.com/typestyle/csstips/blob/master/src/box.ts#L124
Type assertion to CSSProperties should be one level higher on object literal that's returned.

### To reproduce:

- versions:
typescript 2.4.0
├── csstips@0.2.1
├─┬ typestyle@1.3.4

```ts
const styles = {
  root: style(css.horizontal, css.horizontallySpaced(10)),
};
// [ts] Argument of type '{ '&>*': { marginRight: string; }; '&>*:last-child': CSSProperties; }' is not assignable to parameter of type 'NestedCSSProperties | null | undefined'.
  Type '{ '&>*': { marginRight: string; }; '&>*:last-child': CSSProperties; }' has no properties in common with type 'NestedCSSProperties'.
```

**Comment by piotrwitek** [comment]
Submitted a PR: #7

**Comment by basarat** [comment]
Cheers 0.2.2 🌹
