### ISSUE TITLE
use harmony imports

### ISSUE THREAD

**Issue by cyberhck** [typestyle/csstips#8]
Change From
`import * as types from "typestyle/lib/types"`
To
`import types from "typestyle/lib/types"`

Webpack3 has a module concatenation plugin which relies on using harmony imports. I understand this won't work just by changing imports, but if you enable [allowSyntheticDefaultImports](https://www.typescriptlang.org/docs/handbook/compiler-options.html) it'll work. I can create a PR if you're interested. :slightly_smiling_face:

**Comment by basarat** [comment]
`lib/types` has weight `0` on bundle. So not required :rose:

**Comment by cyberhck** [comment]
I'm having a hard time because of this import. Current types is not compatiable with webpack 3's module concatenation plugin.

**Comment by basarat** [comment]
"* as" is a harmony import. And the correct one at that (not synthetic)

**Comment by basarat** [comment]
I can empathise. Trying to protect you from future bugs 🌹
